# Traces the "onegate®" wordmark out of the supplied logo into one SVG path: src/wordmark-path.js
# The letters are read from the artwork itself (6x Lanczos upscale, threshold at mid grey, potrace curves),
# so the site sets the exact logo lettering instead of a font that looks close.
# Usage: python scripts/trace-wordmark.py   (needs: pip install potracer)
import json, os
import numpy as np
import potrace
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), '..')
SCALE = 6
img = Image.open(os.path.join(ROOT, 'public', 'onegate.png')).convert('RGB')
arr = np.asarray(img).astype(np.int32)
white = arr.min(axis=2)
# The lettering sits on the dark band in the middle of the artwork.
region = white[520:720, 300:980]
ys, xs = np.nonzero(region > 140)
pad = 6
x0, x1 = xs.min() + 300 - pad, xs.max() + 300 + pad + 1
y0, y1 = ys.min() + 520 - pad, ys.max() + 520 + pad + 1
crop = img.crop((x0, y0, x1, y1))
big = crop.resize((crop.width * SCALE, crop.height * SCALE), Image.LANCZOS)
mask = np.asarray(big).astype(np.int32).min(axis=2) > 128

paths = potrace.Bitmap(~mask).trace(turdsize=12, turnpolicy=potrace.POTRACE_TURNPOLICY_MINORITY, alphamax=1.0, opticurve=True, opttolerance=0.2)
f = lambda v: f'{v / SCALE:.2f}'.rstrip('0').rstrip('.')
pt = lambda p: f'{f(p.x)} {f(p.y)}'
parts = []
for curve in paths:
    parts.append('M' + pt(curve.start_point))
    for seg in curve.segments:
        if seg.is_corner:
            parts.append('L' + pt(seg.c) + 'L' + pt(seg.end_point))
        else:
            parts.append('C' + pt(seg.c1) + ' ' + pt(seg.c2) + ' ' + pt(seg.end_point))
    parts.append('Z')
d = ''.join(parts)
w, h = x1 - x0, y1 - y0
out = os.path.join(ROOT, 'src', 'wordmark-path.js')
with open(out, 'w', encoding='utf-8', newline='\n') as fh:
    fh.write('// Generated by scripts/trace-wordmark.py from public/onegate.png. Do not edit by hand.\n')
    fh.write(f'export const WORDMARK = Object.freeze({{ width: {w}, height: {h}, d: {json.dumps(d)} }});\n')
crop.save(os.path.join(ROOT, 'artifacts', 'redo', 'wordmark-source.png'))
print('box', (x0, y0, x1, y1), 'size', w, h, 'curves', len(paths), 'path chars', len(d))
